Repository hassio-addons/addon-debian-base, pull requests merged in 2022-06, with the labels that each got.

#111 :arrow_up: Upgrade s6-overlay from 2.2.0.3 to 3.1.0.1
  base/Dockerfile
  base/rootfs/etc/cont-finish.d/99-message.sh
  base/rootfs/etc/cont-init.d/00-banner.sh
  base/rootfs/etc/cont-init.d/01-log-level.sh
  base/rootfs/usr/bin/service
Labels: breaking-change, dependencies

#112 :arrow_up: Upgrades Debian to Bullseye 20220527
  base/Dockerfile
  base/build.yaml
Labels: dependencies

#108 Configure timezone automatically
  base/rootfs/etc/cont-init.d/02-set-timezone.sh
Labels: bugfix

#113 ⬆️ Upgrades s6-overlay to v3.1.1.0
  base/Dockerfile
Labels: dependencies

#114 ⬆️ Upgrades s6-overlay to v3.1.1.1
  base/Dockerfile
Labels: dependencies
